name: Lint

on:
  push:
    branches: [main,"go*"]
  pull_request:
    branches: ["*"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure git
        run: git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/

      - name: Lint
        run: make lint

env:
  GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
  GO_VERSION: '1.20'
